disabled_rules:
  - force_cast
  - missing_docs
opt_in_rules:
  - empty_count
included:
  - TPP
excluded:
  - Pods

force_try:
  severity: warning
line_length: 180
type_body_length:
  - 300
  - 400
file_length:
  warning: 500
  error: 1200
type_name:
  min_length: 4
  max_length:
    warning: 40
    error: 60
  excluded: iPhone
variable_name:
  min_length:
    warning: 3
  max_length:
    warning: 50
    error: 60
  excluded:
    - id
    - URL
    - GlobalAPIKey
reporter: "xcode" #(xcode, json, csv, checkstyle, junit)